# Generated by Django 5.0 on 2023-12-26 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.DateTimeField(blank=True, null=True)),
                ('kpi_1', models.FloatField(blank=True, null=True)),
                ('kpi_2', models.FloatField(blank=True, null=True)),
                ('kpi_3', models.FloatField(blank=True, null=True)),
                ('kpi_4', models.FloatField(blank=True, null=True)),
                ('kpi_5', models.FloatField(blank=True, null=True)),
                ('kpi_6', models.FloatField(blank=True, null=True)),
                ('kpi_7', models.FloatField(blank=True, null=True)),
                ('kpi_8', models.FloatField(blank=True, null=True)),
                ('kpi_9', models.FloatField(blank=True, null=True)),
                ('kpi_10', models.FloatField(blank=True, null=True)),
                ('kpi_11', models.FloatField(blank=True, null=True)),
                ('kpi_12', models.FloatField(blank=True, null=True)),
                ('kpi_13', models.FloatField(blank=True, null=True)),
                ('kpi_14', models.FloatField(blank=True, null=True)),
                ('kpi_15', models.FloatField(blank=True, null=True)),
                ('kpi_16', models.FloatField(blank=True, null=True)),
                ('kpi_17', models.FloatField(blank=True, null=True)),
                ('kpi_18', models.FloatField(blank=True, null=True)),
                ('kpi_19', models.FloatField(blank=True, null=True)),
                ('kpi_20', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
