# Generated by Django 5.0 on 2023-12-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('kpi', models.FloatField()),
            ],
        ),
    ]
