# Generated by Django 5.0 on 2023-12-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro1.raw')),
            ],
        ),
    ]
